config/routes.rb
Bboard::Application.routes.draw do

  get "/home" => "home#index"

  match "show_report"  => "home#show_report"

root :to => 'home#index'

resources :reports do
  collection do
    get 'association'
    get 'attributes'
    get 'operation' 
    get 'finalsubmit'
    post 'create_join'
    put 'publish'
    put 'update'
  end
end
    
resources :order_reports do
    collection do
      get 'filter'
      post 'result'
    end
  end

resources :mem_reports do
   collection do
     get 'bookdetail'
   end 
 end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "user_layout"
  def index
  	@reports = Report.all
  end

  def show_report
  	@report_data = Admin.information(params[:id])
  	data,total = Admin.retrive_data(params[:id],params["where"]||{},params["having"]||{},params[:page])
    p data
    @report_op = WillPaginate::Collection.create(params[:page] || 1, 10,total) do |pager|
      pager.replace(data)
    end
    # p @report_op
  end
end

app/views/home/index.html.erb
<h1>Available Reports</h1>

<table class="table table">
	<tr>
		<th>
			Name
		</th>
		<th>
			View
		</th>
	</tr>

	<%- @reports.each do |rep| %>
		<tr>
			<td>
				<%= rep.description %>
			</td>
			<td>
				<%=  link_to "View", "/show_report?id=#{rep.id}" %>
			</td>
		</tr>
	<% end %>
</table>

<% if @reports.empty? %>
	No Reports Found
<% end %>

<%=  link_to "Add a new report", new_report_path %>

app/views/home/show_report.html.erb
<h1> Report >> <%= @report_data["description"] %> </h1>
<div class="row-fluid">
	<%= form_tag "/show_report", :method => "get"  do %>
		<%= hidden_field_tag :id,params[:id] %>
		<% where=  @report_data["exposed_where_values"]||[] %>
		<% where.each do |where_cdn| %>
			<b><%= where_cdn["label"] %></b>
			<% 
				temp = "#{where_cdn['table']}.#{where_cdn['attribute']}" 
				key = 'where['+temp+']'
				selected_val = params["where"][temp] rescue nil
			%>
			<% if where_cdn["which_table"].present? %>
				<%= select_tag key , options_for_select(populate_list(where_cdn["which_table"],where_cdn["which_field"],where_cdn["which_field_to_show"]),selected_val) %>
			<% else %>
				<%= text_field_tag key,selected_val %>
			<% end %>
		<% end %>
		<br/>
		<% having_arr = @report_data["exposed_having_values"] || [] %>
		<%- having_arr.each do |having| %>
			<b><%= having["label"] %></b>
			<% 
				temp = "#{having['table']}.#{having['attribute']}" 
				key = 'having['+temp+']'
				selected_val = params["having"][temp] rescue nil
			%>
			<% if having["which_table"].present? %>

				<%= select_tag key , options_for_select(populate_list(having["which_table"],having["which_field"],having["which_field_to_show"]),selected_val) %>
			<% else %>
				<%= text_field_tag key,selected_val %>
			<% end %>
		<% end %>
		<br/>
		<%= submit_tag "Filter", :class => "pull-right btn btn-default" %>
	<% end %>
	<br/>
	<br/>
</div>

<table class="table table">
	<tr>
		<%- @report_data["expected_values"].each do |value| %>
			<th>
				<%= value %>
			</th>
		<% end %>	
	</tr>
	<% @report_op.each do |op| %>
		<tr>
			<%- @report_data["expected_values"].each do |value| %>
				<td>	
					<%= op[value] %>
				</td>
			<% end %>
		</tr>
	<% end %>

</table>
<%= will_paginate(@report_op) %>
<%=  link_to "Dashboard", home_path %>