config/routes.rb
Bboard::Application.routes.draw do

  get "/home" => "home#index"

  match "show_report"  => "home#show_report"

root :to => 'home#index'

resources :reports do
  collection do
    get 'association'
    get 'attributes'
    get 'operation' 
    get 'finalsubmit'
    post 'create_join'
    put 'publish'
    put 'update'
  end
end
    
resources :order_reports do
    collection do
      get 'filter'
      post 'result'
    end
  end

resources :mem_reports do
   collection do
     get 'bookdetail'
   end 
 end

end

app/models/order_report.rb
class OrderReport < ActiveRecord::Base
    set_table_name 'temp2ibtrves'

	def self.result(fromdate,todate)
        conditions=[]
        conditions[0]='' 
        if fromdate
        	fromdate=fromdate.to_time.to_i
            conditions[0] << "created_at_int >= ? "
            conditions << fromdate
        end
 
        if todate
        	todate=todate.to_time.to_i
            conditions[0] << "and created_at_int <= ? "
            conditions << todate
        end
                        
        obj=OrderReport.where(conditions)
		states = obj.select("Flag_Destination,State,Count(*) As Num").group("Flag_Destination,State").order("State")
       # p states[0].state
        missing_books_D = obj.select("1").where("book_state = 1 and flag_destination = 'D'").group("ibtr_id")
       # p missing_books.length
        missing_books_S = obj.select("1").where("book_state = 1 and flag_destination = 'S'").group("ibtr_id")
        cancelled_by_member =obj.select("count(*) as cancelled_by_member").where("state = 'Cancelled' and created_by = 13190")
        cancelled_by_ops =obj.select("count(*) as cancelled_by_ops").where("state = 'Cancelled' and created_by != 13190")
      # p cancelled_by_member[0]["cancelled_by_member"]
      # p cancelled_by_ops[0]["cancelled_by_ops"]
        fulfilled_in_n_days =  obj.select("count(*) as fulfilled_in_n_days,ceil((updated_at_int - created_at_int)/(3600*24)) as days,Flag_Destination ").where("state = 'Fulfilled'").group("ceil((updated_at_int - created_at_int)/(3600*24)),Flag_Destination")
      # p fulfilled_in_1day[0].days  
        result = {}
        result["states"] = states
        result["missing_books_D"] = missing_books_D.length
        result["missing_books_S"] = missing_books_S.length
        result["cancelled_by_member"] = cancelled_by_member[0]["cancelled_by_member"]
        result["cancelled_by_ops"] = cancelled_by_ops[0]["cancelled_by_ops"]
        result["fulfilled_in_n_days"] = fulfilled_in_n_days

        result          
	end
end

app/controllers/order_reports_controller.rb
class OrderReportsController < ApplicationController

	def filter
	end

	def result
		@dates = params[:dates]	
		@fromdate=(@dates["fromdate(3i)"] + '-' +@dates["fromdate(2i)"] + '-' + @dates["fromdate(1i)"]).to_time
		@todate=(@dates["todate(3i)"] + '-' +@dates["todate(2i)"] + '-' + @dates["todate(1i)"]).to_time
		@result=OrderReport.result(@fromdate,@todate)
		@states = @result["states"]
		@fulfilled_in_n_days = @result["fulfilled_in_n_days"]
	end

	def choose
	end
end

app/views/order_reports/choose.html.erb
<%= link_to 'Orders Report',filter_order_reports_path %>
<%= link_to 'Members Report',new_mem_report_path %>

app/views/order_reports/filter.html.erb
<h3>Orders Report</h3>



<%= form_tag(result_order_reports_path, :method => "post") do %>
  Fromdate:
<%= date_select("dates","fromdate", start_year: 1995)%>
</br></br>Todate:
<%= date_select("dates","todate", start_year: 1995)%>
</br></br>
<%= submit_tag "Search" %>
<% end %>

app/views/order_reports/result.html.erb
<h1>Order_report</h1>
<h1> DD orders </h1>

<% @one_day_D =0 %>
<% @two_days_D =0 %>
<% @more_days_D =0 %>
<% @one_day_S =0 %>
<% @two_days_S =0 %>
<% @more_days_S =0 %>


<% @fulfilled_in_n_days.each do |x| %>
  <% if x.flag_destination == 'D' %>
    <% if x.days == 1 %>
         <% @one_day_D+=x.fulfilled_in_n_days %>
    <% elsif x.days == 2 %>
         <% @two_days_D+=x.fulfilled_in_n_days %>
    <% else %>
         <% @more_days_D+=x.fulfilled_in_n_days %>
    <% end %>
  <% end %>

  <% if x.flag_destination == 'S' %>
    <% if x.days == 1 %>
         <% @one_day_S+=x.fulfilled_in_n_days %>
    <% elsif x.days == 2 %>
         <% @two_days_S+=x.fulfilled_in_n_days %>
    <% else %>
         <% @more_days_S+=x.fulfilled_in_n_days %>
    <% end %>
  <% end %>

<% end %>





<% @states.each do |x| %>

    <% if x.flag_destination == 'D' %>
			<div>
			      <table border:2px>
				   	<td><%= x.state %></td>
				   	<td><%= x.num %></td>
				   </table>
			</div>
    <% end %>
<% end %>

<h2> Missing Books:</h2><%= @result["missing_books_D"] %>
<h2> Fulfillment in </h2>
<h3> One Day </h3>
<%= @one_day_D %>   

<h3> two Day </h3>
<%= @two_days_D %>       	

<h3> more Day </h3>
<%= @more_days_D %>  




<h1> IBT orders </h1>
<% @states.each do |x| %>

    <% if x.flag_destination == 'S' %>
			<div>
			      <table border:2px>
				   	<td><%= x.state %></td>
				   	<td><%= x.num %></td>
				   </table>
			</div>
    <% end %>
<% end %>

<h2> Missing Books </h2>
<%= @result["missing_books_S"] %>


<h2> Fulfillment in </h2>
<h3> One Day </h3>
<%= @one_day_S %>   

<h3> two Day </h3>
<%= @two_days_S %>       	

<h3> more Day </h3>
<%= @more_days_S %>  



<div align = "center">
<h2> Cancellation of orders </h2>
<h2> By Member : </h2>
<%= @result["cancelled_by_member"] %>

<h2> By ops : </h2>
<%= @result["cancelled_by_ops"] %>
</div>