config/routes.rb
Bboard::Application.routes.draw do

  get "/home" => "home#index"

  match "show_report"  => "home#show_report"

root :to => 'home#index'

resources :reports do
  collection do
    get 'association'
    get 'attributes'
    get 'operation' 
    get 'finalsubmit'
    post 'create_join'
    put 'publish'
    put 'update'
  end
end
    
resources :order_reports do
    collection do
      get 'filter'
      post 'result'
    end
  end

resources :mem_reports do
   collection do
     get 'bookdetail'
   end 
 end

end

app/models/mem_report.rb
class MemReport < ActiveRecord::Base
  attr_accessible :branch_id, :day_limit, :from_book, :from_date, :plan_id, :to_book, :to_date


	def find_members
		    m_cdn = []
		    m_cdn[0] = ""
	    	if branch_id.present?
	    		m_cdn[0] << "branch_id = ? and"
	    		m_cdn <<  branch_id
	    	end	 
		    if plan_id.present? 
		    	m_cdn[0] << " plan_id = ? and"
		    	m_cdn <<  plan_id
		    end
		    if day_limit == "custom"
		    	m_cdn[0] << " issue_date >= ? and issue_date <= ?"
                m_cdn << from_date 
                m_cdn << to_date 
            end     
		    if day_limit == "oneweek"
		    	m_cdn[0] << " issue_date >= ?"
		    	m_cdn << Time.zone.today-1.week
		   	end
		   	if day_limit == "onemonth"
		    	m_cdn[0] << " issue_date >= ?"
		    	m_cdn << Time.zone.today-6.year
		   	end
		  select = 'member_plan_id, min(branch_id) as b_id, count(*) as tot , min(plan_id) as p_id , min(member_profile_id) as m_p_id'	
		  EtlCirculation.select('member_plan_id, min(branch_id) as b_id, count(*) as tot , min(plan_id) as p_id , min(member_profile_id) as m_p_id').where(m_cdn).group(:member_plan_id).having("count(1) >= ? and count(1) <= ? ", from_book,to_book) 		      
		     
	end


	def book_details(a)
			book_detail = [] 
		    m_cdn = []
		    m_cdn[0] = ""
	    	m_cdn[0] << "member_plan_id =  ? and"
	    	m_cdn << a
	    	if day_limit == "custom"
		    	m_cdn[0] << " issue_date >= ? and issue_date <= ?"
                m_cdn << from_date 
                m_cdn << to_date      
		    elsif day_limit == "oneweek"
		    	m_cdn[0] << " issue_date >= ?"
		    	m_cdn << Time.zone.today-1.week
		   	elsif day_limit == "onemonth"
		    	m_cdn[0] << " issue_date >= ?"
		    	m_cdn << Time.zone.today-1.month
		   	end	

		EtlCirculation.where(m_cdn)
	end

end

app/controllers/mem_reports_controller.rb
class MemReportsController < ApplicationController

require 'will_paginate/array'
	def new
	   	@mbook_report = MemReport.new
	  end
	  
	  def create
		 @mbook_report = MemReport.create(params[:mem_report])
	  	if @mbook_report.save
	    	redirect_to mem_report_path(:id => @mbook_report.id)
	    else
	      render :action => 'new'
	    end
	  end

	  def show
	  	 @filter = MemReport.find(params[:id])
	  	 @rep = @filter.find_members().paginate :page => (params[:page].blank? ? 1 : params[:page]), :per_page => (params[:per_page] ||20)
	  end

	  def bookdetail
	  	  @bdetail = MemReport.find(params["filter_id"]).book_details(params["id"].to_i)
	  end

	  
end

app/views/mem_reports/bookdetail.erb
<h3>Book History</h3>
<br/>
<br/>


<% if @bdetail && !@bdetail.empty? %>
  <table class="table table-condensed">
    <tr>
      <th>Member Name</th>
      <th>Member Plan Id</th>
      <th>Title :</th>
    </tr>
    <tr>
      <td>
        <%= EtlMemberProfileInfo.find_by_id(@bdetail.first.member_profile_id).name %>
      </td>
      <td>
        <%= @bdetail.first.member_plan_id%>
      </td>
           <td>
        <% @bdetail.each do |mp| %>
            
            <%= EtlTitle.find_by_id(mp.title_id).title %>
              
               <br>
            
        <% end %>
        </td>
      <br>
     </tr>
  </table>
  <div class="clear"></div>
  <!-- %center= will_paginate(@rep, :params => {:controller => 'accounts', :action => "rep", :format => :js}, :param_name => "rewards_page")
  -->
<% else %>
  No returns till date
<% end %>
</div>

app/views/mem_reports/new.html.erb
<h3>Member Book Report</h3>

<%= form_for @mbook_report  do |f| %>
     
     <div class="field">
     <span class="span-3"><%= f.label :branch_id %></span>
      <%= f.collection_select :branch_id, EtlBranch.where("category=? or category=? ",'S','P').order(:id), :id, :name,:include_blank => 'All Branches' %>
    </div>
    
     <div class="field">
        <span class="span-3"><%= f.label :plan_id %></span>
          <%= f.collection_select :plan_id, EtlPlan.order(:name), :id,  :name, :include_blank => 'All Plans' %>
     </div>
  
  
   <div class="span-6" id = "limitshow">
    <span class="span-3"><%= f.label :day_limit %></span>
     <div>
     <%= f.select "day_limit",
      options_for_select([['last one week',"oneweek"],['last one month',"onemonth"],['Custom',"custom"]]) %>
    </div>
   </div>
    <br/>
    <div id="fromtodate" hidden { display: none;} >
      <div class="span-12">
        <div class = "span-3" style = font-weight:bold; >From </div>
          <%= f.date_select :from_date %>
        </div>
        <div class="span-12">
          <div class = "span-3" style = font-weight:bold; >To</div>
            <%= f.date_select :to_date %>
          </div>
        </div>
    </div>




   
  <br/>
  <br/>

  <div class="span-12">
    <div class="span-3" style = font-weight:bold; > Minbook </div>
    <%= f.number_field :from_book , :style => "width:50px"%>
  </div>
  <br>
  <br>
  <br>
  <br>
  <br>
  <div class="span-12">
    <div class="span-3" style = font-weight:bold; > Maxbook </div>
    <%= f.number_field(:to_book, :style => "width:50px")  %>
  </div>
<br/>


  <div class ="span-24">
    <br/>
    <br/>
    <div class="actions"><%= f.submit "Search" %></div>
  </div>
<% end %>

app/views/mem_reports/show.html.erb
<h3>Member Details</h3>
<br/>
<br/>
<%= will_paginate @rep %>
<table class="table table-condensed">
    <tr>
      <th>Selected Branch</th>
      <th>Selected Plan</th>
      <th>Min Book</th>
      <th>Max Book</th>
      <th>Date Type</th>
      
    </tr>
    <tr>
      <td>
        <% if @filter.branch_id.nil?%>
        <%= "All"%>
        <% else %>
        <%=  EtlBranch.where(:id => @filter.branch_id).first.name%>
        <%end%>
      </td>
      <td>
        <% if @filter.plan_id.nil?%>
        <%= "All"%>
        <% else %>
        <%=  EtlPlan.where(:id => @filter.plan_id).first.name%>
        <%end%>
      </td>
      <td>
        <%= @filter.from_book%>
      </td>
      <td>
        <%= @filter.to_book%>
      </td>  
      <td>
        <% if @filter.day_limit == 'all'%>
          <%= "All"%>
        <% elsif  @filter.day_limit == 'oneweek'%>
          <%=  "Last week"%>
         <% elsif  @filter.day_limit == 'onemonth'%>
          <%=  "Last month"%>
         <% else %>
          <%="From date: #{@filter.from_date.to_date}"%>
          <%="To date: #{@filter.to_date.to_date}"%>
        <%end%>
      </td>
    </tr>
  </table>
  <br/>
  <br/>    

<div>
  
<% if @rep && !@rep.empty? %>
  <table class="table table-condensed">
    <tr>
      <th>Member Name</th>
      <th>Plan</th>
      <th>count</th>
      <th>Branch</th>
    </tr>
    <% @rep.each do |mp| %>
      <tr>
        <td>
          <%= EtlMemberProfileInfo.find_by_id(mp.m_p_id).name %>
        </td>
        <td>
          <%= EtlPlan.find_by_id(mp.p_id).name %>
        </td>
       <td>
        <%=  %>
        <%=link_to mp.tot , bookdetail_mem_reports_path(id: mp.member_plan_id ,filter_id: @filter.id) %>
      </td>
        <td>
          <%=  EtlBranch.find_by_id(mp.b_id).name%>
        </td>
      </tr>
    <% end %>
  </table>
  <div class="clear"></div>
  <!-- %center= will_paginate(@rep, :params => {:controller => 'accounts', :action => "rep", :format => :js}, :param_name => "rewards_page")
  -->
<% else %>
  No returns till date
<% end %>
</div>